# Generated by Django 3.2.8 on 2022-07-15 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discuss', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='account_state',
            field=models.BooleanField(default=True),
        ),
    ]
