# Generated by Django 3.2.8 on 2022-07-15 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discuss', '0002_users_account_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_title', models.TextField(max_length=50)),
                ('question_body', models.TextField(max_length=500)),
                ('q_upvotes', models.IntegerField(default=0)),
                ('q_downvotes', models.IntegerField(default=0)),
                ('is_blocked', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
