# Generated by Django 3.2.8 on 2022-07-15 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discuss', '0003_questions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(max_length=200)),
                ('upvotes', models.IntegerField(default=0)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_accepted', models.BooleanField(default=True)),
                ('is_blocked', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='questions',
            name='answers',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='discuss.answers'),
            preserve_default=False,
        ),
    ]
