# Generated by Django 3.2.8 on 2022-07-15 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discuss', '0006_alter_questions_answers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='answers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discuss.answers'),
        ),
    ]
