# Generated by Django 3.2.8 on 2022-07-15 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discuss', '0007_alter_questions_answers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='answers',
        ),
    ]
