# Generated by Django 3.2.8 on 2022-07-15 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discuss', '0008_remove_questions_answers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Answers',
        ),
    ]
