# Generated by Django 3.2.8 on 2022-07-15 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discuss', '0009_delete_answers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(max_length=200)),
                ('upvotes', models.IntegerField(default=0)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_accepted', models.BooleanField(default=True)),
                ('is_blocked', models.BooleanField(default=False)),
            ],
        ),
    ]
